- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /etc/pki/tls/certs
    - /etc/pki/tls/private

- name: Check if certificates exist
  stat: path=/etc/pki/tls/certs/server.crt
  register: cert_exists

- name: Issue certificate
  vault_issue_pki_int:
    url: https://scoring.sa.cs.ut.ee:8200
    role_name: "{{ domain_name }}"
    token: "{{ token }}"
    common_name: "{{ hostname }}.{{ domain_name }}"
    alt_names:
      - www."{{ hostname }}.{{ domain_name }}"
      - mail."{{ hostname }}.{{ domain_name }}"
      - wordpress."{{ hostname }}.{{ domain_name }}"
      - proxy."{{ hostname }}.{{ domain_name }}"
  register: cert
  when: not cert_exists.stat.exists or not cert_exists.stat.isreg

- name: Write certificates
  copy:
    content: "{{ item.content }}"
    dest: "{{ item.dest }}"
  loop:
    - {
        content: "{{ cert.data.data.certificate }}",
        dest: /etc/pki/tls/certs/server.crt,
      }
    - {
        content: "{{ cert.data.data.private_key }}",
        dest: /etc/pki/tls/private/server.key,
      }
    - {
        content: "{{ cert.data.data.issuing_ca }}",
        dest: /etc/pki/tls/certs/cacert.crt,
      }
  loop_control:
    label: "{{ item.dest }}"
  when: not cert_exists.stat.exists or not cert_exists.stat.isreg
