- name: Install Apache
  dnf:
    name:
      - httpd
      - mod_ssl
    state: latest

- name: Firewall add HTTP service
  firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: yes

- name: Firewall add HTTPS
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - 443/udp
    - 443/tcp

- name: Enable httpd service
  systemd:
    name: httpd
    enabled: yes
    state: started

- name: Set up www virtual host
  include: www.yml
  tags: www

- name: Set up proxy virtual host
  include: proxy.yml
  tags: proxy

- name: Set up Wordpress
  include: wordpress.yml
  tags: wordpress

- name: Set up Apache modules
  include: modules.yml
