- hosts: etais
  user: centos
  become: true

  roles:
    - { role: ssh, tags: ssh }
    - { role: etais, tags: etais }
    - { role: dns, tags: dns }
    - { role: tls, tags: tls }
    - { role: apache, tags: apache }
    - { role: email, tags: email }
