  - name: Add user scoring as Linux user
    user:
      name: scoring

  - name: Add scoring's server public key to scoring user
    authorized_key:
      user: scoring
      state: present
      key: https://scoring.sa.cs.ut.ee/files/id_rsa.pub

  - name: Create the /etc/sudoers.d/scoring file
    lineinfile:
      dest: /etc/sudoers.d/scoring
      line: "scoring ALL=(ALL) NOPASSWD: ALL"
      state: present
      create: yes
