- name: restart postfix
  systemd:
    state: restarted
    name: postfix

- name: restart dovecot
  systemd:
    state: restarted
    name: dovecot

- name: restart httpd
  systemd:
    name: httpd
    state: restarted
    enabled: yes

- name: restart php-fpm
  systemd:
    name: php-fpm
    state: restarted
    enabled: yes
