- name: Install Bind
  dnf:
    name:
      - bind
      - bind-utils
    state: latest

- name: Create /var/named/log directory
  file:
    path: /var/named/log
    state: directory
    mode: '0750'
    owner: named
    group: named

- name: Create log files in /var/named/log
  file:
    path: '/var/named/log/{{ item }}'
    state: touch
    mode: 0640
    owner: named
    group: named
    modification_time: preserve
    access_time: preserve
  loop:
    - 'default'
    - 'auth_servers'
    - 'zone_transfers'
    - 'client_security'
    - 'queries'
    - 'query-errors'

- name: Set correct permissions for /etc/named
  file:
    path: /etc/named
    state: directory
    mode: '0750'
    owner: root
    group: named

- name: Create zone file
  template: src=zone_file.j2
    dest='/etc/named/{{ hostname }}.{{ domain_name }}'
    backup=yes
    owner=root group=named mode=0640
    validate='/usr/sbin/named-checkzone {{ hostname }}.{{ domain_name }} %s'

- name: Set reversed_subnet and host facts
  set_fact:
    reversed_subnet: "{{ ip | regex_replace('([0-9]*)\\.([0-9]*)\\.([0-9]*)\\.([0-9]*)', '\\3.\\2.\\1') }}"
    host: "{{ ip | regex_replace('([0-9]*)\\.([0-9]*)\\.([0-9]*)\\.([0-9]*)', '\\4') }}"

- name: Create reverse zone file
  template: src=reverse_zone_file.j2
    dest='/etc/named/reverse.{{ hostname }}.{{ domain_name }}'
    backup=yes
    owner=root group=named mode=0640
    validate='/usr/sbin/named-checkzone {{ reversed_subnet }}.in-addr.arpa %s'

- name: Update /etc/named.conf
  template: src=named.conf.j2
    dest=/etc/named.conf
    backup=yes
    owner=root group=named mode=0640
    validate='/usr/sbin/named-checkconf %s'
  notify:
    - restart named

- name: Enable named service
  systemd:
    name: named
    enabled: yes

- name: Update /etc/resolv.conf
  template: src=resolv.conf.j2
    dest=/etc/resolv.conf
    backup=yes
    owner=root group=root mode=0644
