- name: Firewall add DNS service
  firewalld:
    service: dns
    permanent: yes
    state: enabled
    immediate: yes

- name: Firewall add port 8301
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - 8301/udp
    - 8301/tcp
